# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cont_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



# from msilib.schema import Dialog
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget,QDialog,QAbstractButton
from config import Row_checked, Shard_table
import sys
sys.path.append("ui")
from contact import Ui_dialog


class Ui_Form(object):
    def setupUi(self, Form,num_recs):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(850, 450)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        Form.setFont(font)
        Form.setFocusPolicy(QtCore.Qt.StrongFocus)
        Form.setAutoFillBackground(False)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(140, 360, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        # 
        self.pushButton.clicked.connect(self.ins_rec)    
        # 
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 360, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        # кнопка удалить
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(560, 360, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        # 
        self.pushButton_3.clicked.connect(self.del_rec)    
        # 
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(600, 10, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(560, 10, 21, 21))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui/customer_icon.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(90, 40, 750, 301))
        self.tableWidget.setMinimumSize(QtCore.QSize(671, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
         # установка количества строк в таблице
        self.tableWidget.setRowCount(num_recs)
        # установка количества колонок в таблице
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(1, 2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(219)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(200)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        # установка ширины первого столбца
        # 
        self.tableWidget.setColumnWidth(0, 300)
        # 
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(23)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(350, 10, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(500, 10, 30, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(100, 10, 175, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(280, 10, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(5, 40, 80, 41))
        self.comboBox.setMaxVisibleItems(14)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(Form)
        self.tableWidget.cellClicked['int','int'].connect(self.label_4.setNum)
        self.comboBox.activated['QString'].connect(self.label_6.setText)
        self.comboBox.activated['QString'].connect(self.part_table)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "База данных"))
        self.pushButton.setText(_translate("Form", "Добавить"))
        self.pushButton_2.setText(_translate("Form", "Сохранить"))
        self.pushButton_3.setText(_translate("Form", "Удалить"))
        self.label_2.setText(_translate("Form", "Зашли как: "+User_name))
        # 
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Имя"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Телефон"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Дата рождения"))
        # 
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("Form", "Выбрана строка:"))
        self.label_5.setText(_translate("Form", "Выбраны фамилии на:"))
        self.comboBox.setItemText(0, _translate("Form", "АБ"))
        self.comboBox.setItemText(1, _translate("Form", "ВГ"))
        self.comboBox.setItemText(2, _translate("Form", "ДЕЁ"))
        self.comboBox.setItemText(3, _translate("Form", "ЖЗИ"))
        self.comboBox.setItemText(4, _translate("Form", "ЙКЛ"))
        self.comboBox.setItemText(5, _translate("Form", "МН"))
        self.comboBox.setItemText(6, _translate("Form", "ОП"))
        self.comboBox.setItemText(7, _translate("Form", "РС"))
        self.comboBox.setItemText(8, _translate("Form", "ТУ"))
        self.comboBox.setItemText(9, _translate("Form", "ФХ"))
        self.comboBox.setItemText(10, _translate("Form", "ЦЧШ"))
        self.comboBox.setItemText(11, _translate("Form", "ЩЫЭ"))
        self.comboBox.setItemText(12, _translate("Form", "ЮЯ"))

    
  #  обработка нажатия кнопок
  # обработка кнопки добавить
    def ins_rec (self):
      # 
      Dialog = QtWidgets.QDialog()
      edit_params__QD = Ui_dialog()
      ui = Ui_dialog()
      ui.setupUi(Dialog)
      Dialog.show()
      if (Dialog.exec_()):
        value1, value2 = edit_params__QD.accept()
        print(value1,value2)
        print('запись соххраненна')
      else:
        print('запись НЕ соххраненна')
      # 
    def part_table(self):
          self.label_6.setText
          Shard_table = str(self.label_6.text())
          shard = "username REGEXP "+ "'^("+"|".join(Shard_table)+")'"
          buffer_recs = getall_recs("tel_dict",shard)
          print(len(buffer_recs))
          fill_table(buffer_recs)
      # 
    def del_rec (self):
      if self.label_4.text() != '':
        print(self.label_4.text())
      else: print('ничего не выбрано')
        # dialog = QtWidgets.QDialog()
        # ui = Ui_dialog()
        # ui.setupUi(dialog)
        # dialog.exec()
        # selectedRanges(), would give you the second cell from each selected row, for example:
        # 
        # indexes = []
        # results = []
        # print("here")
        # myTable = QtWidgets.QTableWidget(Form)
        # 
        # for selectionRange in myTable.selectedRanges():
        #     indexes.extend(range(selectionRange.topRow(), selectionRange.bottomRow()+1))
        #     print ("indexes", indexes)      # indexes is a list like [0, 2] of selected rows
        # for i in indexes:
        #     print ("specific item", myTable.item(i, 1).text())
        #     results.append( str(myTable.item(i, 1).text()) )
        # selectedItems()
        # 
        # for item in myTable.selectedItems():
        #     print("selectedItems", item.text())
        # 
        # # selectedIndexes()
        # for item in myTable.selectedIndexes():
        #     print ("selectedIndexes", item.row(), item.column())
      

# #### блок заполнения таблицы из базы
# чтение записей из таблицы 
def getall_recs(table,filter):
  mycursor = mydb.cursor()
  # sql = f"SELECT * FROM {table} WHERE {filter}"
  if (filter !=''):
    mycursor.execute(f"SELECT * FROM {table} WHERE {filter}")
  else:
     mycursor.execute(f"SELECT * FROM {table}")
  myresult = mycursor.fetchall()
  data = []
  for x in myresult:
    data.append(x)
  return data
# заполнение таблицы из базы
def fill_table(data):
    row = 0
    ui.tableWidget.clear()
    ui.tableWidget.update()
   
    # self.tableWidget.setRowCount(num_recs)
    ui.tableWidget.setRowCount(len(data))
    for tup in data:
      col = 0
      for i in range(1,len(tup)):
        if type(tup[i]) == datetime.date:
          item = tup[i].strftime('%Y-%m-%d')
        else: item = tup[i]
        cellinfo = QtWidgets.QTableWidgetItem(item)
        ui.tableWidget.setItem(row, col, cellinfo)
        if col != 0:
          cellinfo.setTextAlignment(QtCore.Qt.AlignCenter)
        col += 1
      row += 1
# 

if __name__ == "__main__":
    import sys
    import datetime
    from config import link as mydb
    from config import User_name
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    buffer_recs = getall_recs("tel_dict",Shard_table)
    ui.setupUi(Form,len(buffer_recs))
    Form.show()
    # Ui_Form.retranslateUi (Ui_Form, Form)
    fill_table(buffer_recs)
    sys.exit(app.exec_())


