# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wid_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtCore
from PyQt5.QtWidgets import QDialog
import mysql.connector as mc
import sys
sys.path.append("ui")
from config import link as mydb
# from reg import Ui_Dialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(76, 20, 231, 31))
        self.label.setObjectName("label")

        self.lineEditLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditLogin.setGeometry(QtCore.QRect(70, 70, 351, 25))
        self.lineEditLogin.setObjectName("self.lineEditLogin")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 50, 351, 20))
        self.label_2.setObjectName("label_2")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 90, 351, 21))
        self.label_4.setObjectName("label_4")

        self.lineEditPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPassword.setGeometry(QtCore.QRect(70, 110, 351, 25))
        self.lineEditPassword.setObjectName("lineEditPassword")

        # первая кнопка
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 150, 85, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.login)
        # вторая кнопка
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 150, 85, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.reg)
        # третья кнопка
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 150, 85, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        # чек бокс1
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(160, 190, 111, 18))
        self.checkBox.setObjectName("checkBox")
        # чек бокс2
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(160, 220, 111, 18))
        self.checkBox_2.setObjectName("checkBox_2")

        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(160, 250, 171, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # вывод результата запроса
        # self.verticalLayout = QtWidgets.QVBoxLayout()
        # self.verticalLayout.setObjectName("verticalLayout")

        self.labelResult = QtWidgets.QLabel(self.centralwidget)
        self.labelResult.setGeometry(QtCore.QRect(100, 450, 500, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelResult.setFont(font)
        self.labelResult.setText("")
        self.commandLinkButton.adjustSize()
        # self.labelResult.setObjectName("labelResult")
        # self.verticalLayout.addWidget(self.labelResult)
        # self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вход/регистрация"))
        self.label.setText(_translate("MainWindow", "                  Окно авторизации"))
        self.label_2.setText(_translate("MainWindow", "Логин"))
        self.label_4.setText(_translate("MainWindow", "Пароль"))
        self.pushButton.setText(_translate("MainWindow", "Войти"))
        self.pushButton.adjustSize()
        self.pushButton_2.setText(_translate("MainWindow", "Регистрация"))
        self.pushButton_2.adjustSize()
        self.pushButton_3.setText(_translate("MainWindow", "Отмена"))
        self.pushButton_3.adjustSize()
        self.checkBox.setText(_translate("MainWindow", "Запомнить меня"))
        self.checkBox.adjustSize()
        self.checkBox_2.setText(_translate("MainWindow", "Показать пароль"))
        self.checkBox_2.adjustSize()
        self.commandLinkButton.setText(_translate("MainWindow", "Забыли пароль?"))
        self.commandLinkButton.adjustSize()


# обработка кнопки вход
    def login(self):
        try:
            login = self.lineEditLogin.text()
            password = self.lineEditPassword.text()
            remember = self.checkBox.isChecked()
            show_pswd = self.checkBox_2.isChecked()
 
            mycursor = mydb.cursor()
            mycursor.execute("SELECT login,pswd from users where login like '"+login + "'and pswd like '"+password+"'")
            result = mycursor.fetchone()
 
            if result == None:
                self.labelResult.setText("Неправильный пароль или Логин")
                print(remember)
                print(show_pswd)
 
            else:
                self.labelResult.setText("Вы вошли")
                # mydialog = QDialog()
                # mydialog.setModal(True)
                # mydialog.exec()
        except mc.Error as e:
            self.labelResult.setText("Что-то пошло не так!")

    # обработка кнопки регистрация
    def reg(self):
        # mydialog = QDialog(Ui_Dialog)
        # mydialog.setModal(True)
        # mydialog.exec()
        class Ui_Dialog(object):
            # def __init__(self):
                def setupUi(self, Dialog):
                    Dialog.setObjectName("Dialog")
                    Dialog.resize(400, 300)
                    self.label = QtWidgets.QLabel(Dialog)
                    self.label.setGeometry(QtCore.QRect(56, 20, 301, 21))
                    font = QtGui.QFont()
                    font.setFamily("Arial")
                    font.setPointSize(10)
                    font.setBold(True)
                    font.setWeight(75)
                    self.label.setFont(font)
                    self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
                    self.label.setObjectName("label")
                    self.frame = QtWidgets.QFrame(Dialog)
                    self.frame.setGeometry(QtCore.QRect(19, 49, 341, 181))
                    self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                    self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                    self.frame.setLineWidth(2)
                    self.frame.setMidLineWidth(0)
                    self.frame.setObjectName("frame")
                    self.lineEdit = QtWidgets.QLineEdit(self.frame)
                    self.lineEdit.setGeometry(QtCore.QRect(40, 30, 251, 20))
                    font = QtGui.QFont()
                    font.setFamily("Arial")
                    font.setPointSize(10)
                    self.lineEdit.setFont(font)
                    self.lineEdit.setText("")
                    self.lineEdit.setObjectName("lineEdit")
                    self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
                    self.lineEdit_2.setGeometry(QtCore.QRect(40, 60, 251, 20))
                    font = QtGui.QFont()
                    font.setFamily("Arial")
                    font.setPointSize(10)
                    self.lineEdit_2.setFont(font)
                    self.lineEdit_2.setText("")
                    self.lineEdit_2.setObjectName("lineEdit_2")
                    self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
                    self.lineEdit_3.setGeometry(QtCore.QRect(40, 90, 251, 20))
                    font = QtGui.QFont()
                    font.setFamily("Arial")
                    font.setPointSize(10)
                    self.lineEdit_3.setFont(font)
                    self.lineEdit_3.setText("")
                    self.lineEdit_3.setObjectName("lineEdit_3")
                    self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
                    self.lineEdit_4.setGeometry(QtCore.QRect(40, 120, 141, 20))
                    font = QtGui.QFont()
                    font.setFamily("Arial")
                    font.setPointSize(10)
                    self.lineEdit_4.setFont(font)
                    self.lineEdit_4.setText("")
                    self.lineEdit_4.setProperty("Date", QtCore.QDate(0, 0, 0))
                    self.lineEdit_4.setObjectName("lineEdit_4")
                    self.dateEdit = QtWidgets.QDateEdit(self.frame)
                    self.dateEdit.setGeometry(QtCore.QRect(180, 120, 110, 22))
                    self.dateEdit.setObjectName("dateEdit")
                    self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
                    self.buttonBox.setGeometry(QtCore.QRect(100, 220, 161, 32))
                    self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
                    self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
                    self.buttonBox.setObjectName("buttonBox")

                    self.retranslateUi(Dialog)
                    self.buttonBox.accepted.connect(Dialog.accept)
                    self.buttonBox.rejected.connect(Dialog.reject)
                    self.dateEdit.dateChanged['QDate'].connect(self.lineEdit_4.paste)
                    QtCore.QMetaObject.connectSlotsByName(Dialog)
                   

        def retranslateUi(self, Dialog):
            _translate = QtCore.QCoreApplication.translate
            Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
            self.label.setText(_translate("Dialog", "                      Регистрация"))
            self.lineEdit.setPlaceholderText(_translate("Dialog", "Имя пользователя"))
            self.lineEdit_2.setPlaceholderText(_translate("Dialog", "Пароль"))
            self.lineEdit_3.setPlaceholderText(_translate("Dialog", "Повторите пароль"))
            self.lineEdit_4.setPlaceholderText(_translate("Dialog", "Дата рождения"))
        
        class My_Dialog(QDialog, Ui_Dialog):
            def __init__(self):
                super().__init__()
                self.setupUi(self)
        
        self.dialog = My_Dialog()
        self.dialog.exec_()
        # self.dialog.show() 

        # def accept(self):
        # # """Save settings after clicking on OK button"""
        # settings = QtCore.QSettings()
        # settings.setValue("send_client_active", self.sendClientActiveCheckBox.isChecked())
        # settings.setValue("send_read_state", self.sendReadStateCheckBox.isChecked())
        # settings.setValue("enter_send_message", self.enterSendMessageCheckBox.isChecked())
        # settings.setValue("language", self.languageComboBox.itemData(self.languageComboBox.currentIndex()))
        # settings.setValue("connection_events", self.connectionEventsCheckBox.isChecked())
        # settings.setValue("autoconnect", self.autoConnectCheckBox.isChecked())
        # QtWidgets.QDialog.accept(self)