# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtCore
from PyQt5.QtWidgets import QDialog
import mysql.connector as mc
import sys
sys.path.append("ui")
from config import User_name, link as mydb
# from reg import Ui_Dialog


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        mainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # 
        # фрейм
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 40, 441, 331))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        # заголовок
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 0, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        # Логин
        self.lineEditLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditLogin.setGeometry(QtCore.QRect(70, 60, 351, 31))
        self.lineEditLogin.setStatusTip("")
        self.lineEditLogin.setText("")
        self.lineEditLogin.setObjectName("lineEditLogin")
        # Пароль
        self.lineEditPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPassword.setGeometry(QtCore.QRect(70, 120, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setText("")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
       
        # первая кнопка
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 190, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.login)
        # вторая кнопка
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 190, 91, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.reg)
        # третья кнопка
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 190, 101, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.quit)
        # чек бокс1
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(150, 250, 111, 18))
        self.checkBox.setObjectName("checkBox")
         # чек бокс2
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(150, 290, 111, 18))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_2.clicked.connect(self.showpswd)
        
        # линк восстановить пароль
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(170, 320, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.commandLinkButton.setFont(font)
        self.commandLinkButton.setObjectName("commandLinkButton")
        
        # статус сообщение-результат
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        # вывод результата
        self.labelResult = QtWidgets.QLabel(self.centralwidget)
        self.labelResult.setGeometry(QtCore.QRect(70, 450, 500, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.labelResult.setFont(font)
        self.labelResult.setText("")
        self.commandLinkButton.adjustSize()
        self.labelResult.setAlignment(QtCore.Qt.AlignCenter)
        self.labelResult.setObjectName("labelResult")

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Авторизация"))
        self.lineEditLogin.setPlaceholderText(_translate("mainWindow", "Логин"))
        self.lineEditPassword.setPlaceholderText(_translate("mainWindow", "Пароль"))
        self.pushButton.setText(_translate("mainWindow", "Войти"))
        self.pushButton.adjustSize()
        self.pushButton_2.setText(_translate("mainWindow", "Регистрация"))
        self.pushButton_2.adjustSize()
        self.pushButton_3.setText(_translate("mainWindow", "Отмена"))
        self.pushButton_3.adjustSize()
        self.checkBox.setText(_translate("mainWindow", "Запомнить меня"))
        self.checkBox.adjustSize()
        self.checkBox_2.setText(_translate("mainWindow", "Показать пароль"))
        self.checkBox_2.adjustSize()
        self.commandLinkButton.setText(_translate("mainWindow", "Забыли пароль?"))
        self.label.setText(_translate("mainWindow", "Окно авторизации"))

    # # выход
    def quit(self):
        exit()
    # переключение видимости пароля
    def showpswd(self):
        show_pswd = self.checkBox_2.isChecked()
        if show_pswd:
            self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Normal)
        else:
            self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        
# обработка кнопки вход
    def login(self):
        try:
            login = self.lineEditLogin.text()
            password = self.lineEditPassword.text()
            # запомнить пользователя
            remember = self.checkBox.isChecked()
          
 
            mycursor = mydb.cursor()
            mycursor.execute("SELECT login,pswd,username from users where login like '"+login + "'and pswd like '"+password+"'")
            result = mycursor.fetchone()
            mycursor.close()
 
            if result == None:
                self.labelResult.setText("Неправильный пароль или Логин")
                
           
 
            else:
                self.labelResult.setText("Вы вошли")
                if (remember): User_name = result[2] 
                print(User_name)
                # mydialog = QDialog()
                # mydialog.setModal(True)
                # mydialog.exec()
        except mc.Error as e:
            self.labelResult.setText("Что-то пошло не так!")

    # обработка кнопки регистрация
    def reg(self):
        class Ui_Dialog(object):
            def setupUi(self, Dialog):
                Dialog.setObjectName("Dialog")
                Dialog.resize(509, 468)
                self.label = QtWidgets.QLabel(Dialog)
                self.label.setGeometry(QtCore.QRect(80, 10, 301, 21))
                font = QtGui.QFont()
                font.setFamily("Times New Roman")
                font.setPointSize(12)
                font.setBold(False)
                font.setWeight(50)
                self.label.setFont(font)
                self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
                self.label.setAlignment(QtCore.Qt.AlignCenter)
                self.label.setObjectName("label")
                self.frame = QtWidgets.QFrame(Dialog)
                self.frame.setGeometry(QtCore.QRect(50, 40, 401, 301))
                self.frame.setFrameShape(QtWidgets.QFrame.Box)
                self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
                self.frame.setLineWidth(2)
                self.frame.setMidLineWidth(0)
                self.frame.setObjectName("frame")
                # Ввод Логин
                self.lineEdit = QtWidgets.QLineEdit(self.frame)
                self.lineEdit.setGeometry(QtCore.QRect(20, 20, 361, 31))
                font = QtGui.QFont()
                font.setFamily("Times New Roman")
                font.setPointSize(10)
                self.lineEdit.setFont(font)
                self.lineEdit.setText("")
                self.lineEdit.setObjectName("lineEdit")
                # Ввод пароля
                self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
                self.lineEdit_2.setGeometry(QtCore.QRect(20, 70, 361, 31))
                font = QtGui.QFont()
                font.setFamily("Times New Roman")
                font.setPointSize(10)
                self.lineEdit_2.setFont(font)
                self.lineEdit_2.setText("")
                self.lineEdit_2.setObjectName("lineEdit_2")
                #  подтверждение пароля
                self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
                self.lineEdit_3.setGeometry(QtCore.QRect(20, 130, 361, 31))
                font = QtGui.QFont()
                font.setFamily("Times New Roman")
                font.setPointSize(10)
                self.lineEdit_3.setFont(font)
                self.lineEdit_3.setText("")
                self.lineEdit_3.setObjectName("lineEdit_3")
                # фрейм
                self.dateEdit = QtWidgets.QDateEdit(self.frame)
                self.dateEdit.setGeometry(QtCore.QRect(20, 220, 121, 31))
                font = QtGui.QFont()
                font.setFamily("Times New Roman")
                font.setPointSize(9)
                self.dateEdit.setFont(font)
                self.dateEdit.setObjectName("dateEdit")
                self.label_2 = QtWidgets.QLabel(self.frame)
                self.label_2.setGeometry(QtCore.QRect(30, 180, 111, 21))
                font = QtGui.QFont()
                font.setFamily("Times New Roman")
                self.label_2.setFont(font)
                self.label_2.setAlignment(QtCore.Qt.AlignCenter)
                self.label_2.setObjectName("label_2")
                self.calendarWidget = QtWidgets.QCalendarWidget(self.frame)
                self.calendarWidget.setGeometry(QtCore.QRect(220, 170, 141, 121))
                self.calendarWidget.setObjectName("calendarWidget")
                # кнопка ок
                self.pushButton = QtWidgets.QPushButton(Dialog)
                self.pushButton.setGeometry(QtCore.QRect(120, 420, 81, 31))
                self.pushButton.setObjectName("pushButton")
                self.pushButton.clicked.connect(self.do_reg)
                # кнопка отмена
                self.pushButton_2 = QtWidgets.QPushButton(Dialog)
                self.pushButton_2.setGeometry(QtCore.QRect(290, 420, 81, 31))
                self.pushButton_2.setObjectName("pushButton_2")
                self.pushButton_2.clicked.connect(self.close)
                # сообщение - результат
                self.labelResult = QtWidgets.QLabel(Dialog)
                self.labelResult.setGeometry(QtCore.QRect(70, 365, 371, 31))
                font = QtGui.QFont()
                font.setFamily("Times New Roman")
                font.setPointSize(10)
                self.labelResult.setFont(font)
                self.labelResult.setText("")
                self.labelResult.setAlignment(QtCore.Qt.AlignCenter)
                self.labelResult.setObjectName("labelResult")
                # 
                self.retranslateUi(Dialog)
                self.calendarWidget.clicked['QDate'].connect(self.dateEdit.setDate)
                self.dateEdit.dateChanged['QDate'].connect(self.calendarWidget.setSelectedDate)
                QtCore.QMetaObject.connectSlotsByName(Dialog)

            def retranslateUi(self, Dialog):
                _translate = QtCore.QCoreApplication.translate
                Dialog.setWindowTitle(_translate("Dialog", "Регистрация"))
                self.label.setText(_translate("Dialog", "Регистрация"))
                self.lineEdit.setPlaceholderText(_translate("Dialog", "Имя пользователя"))
                self.lineEdit_2.setPlaceholderText(_translate("Dialog", "Пароль"))
                self.lineEdit_3.setPlaceholderText(_translate("Dialog", "Повторите пароль"))
                self.label_2.setText(_translate("Dialog", "Дата рождения"))
                self.pushButton.setText(_translate("Dialog", "OK"))
                self.pushButton_2.setText(_translate("Dialog", "Отмена"))

            # обработка кнопки вход
            def do_reg(self):
                if self.lineEdit_2.text() == self.lineEdit_3.text():
                    try:
                        # запомнить пользователя
                        username = self.lineEdit.text()
                        login = self.lineEdit.text()
                        password = self.lineEdit_2.text()
                        # проверка на наличие дубликата
                        mycursor = mydb.cursor()
                        mycursor.execute("SELECT login,pswd from users where login like '"+login + "'and pswd like '"+password+"'")
                        result = mycursor.fetchone()
                        # mydb.close()
                
                        if result == None:
                            mycursor.execute("""INSERT INTO users(username, login, pswd) VALUES (%s, %s, %s)""",(username, login, password))
                            self.labelResult.setText("Вы зарегистрированы")
                            mydb.commit()
                            # mydb.close()
                            
                        else:
                            self.labelResult.setText("Пользователь с такими данными существует")
                                # mydialog = QDialog()
                                # mydialog.setModal(True)
                                # mydialog.exec()
                    except mc.Error as e:
                        self.labelResult.setText("Что-то пошло не так!"+mc.Error)
                else: 
                    self.labelResult.setText("Пароль не совпадает с введённым!")


        class My_Dialog(QDialog, Ui_Dialog):
            def __init__(self):
                super().__init__()
                self.setupUi(self)
        self.dialog = My_Dialog()
        self.dialog.exec_()