# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contact.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from genericpath import exists
from tkinter import dialog
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(650, 401)
        self.lineEdit = QtWidgets.QLineEdit(dialog)
        self.lineEdit.setGeometry(QtCore.QRect(30, 20, 511, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("xxx")
        # 
        print(self.lineEdit.text())
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.dateEdit = QtWidgets.QDateEdit(dialog)
        self.dateEdit.setGeometry(QtCore.QRect(40, 190, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.calendarWidget = QtWidgets.QCalendarWidget(dialog)
        self.calendarWidget.setGeometry(QtCore.QRect(240, 70, 301, 181))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setObjectName("calendarWidget")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(30, 150, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(dialog)
        self.pushButton.setGeometry(QtCore.QRect(180, 280, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 280, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(dialog)
        self.calendarWidget.clicked['QDate'].connect(self.dateEdit.setDate)
        self.dateEdit.dateChanged['QDate'].connect(self.calendarWidget.setSelectedDate)
        self.pushButton.clicked.connect(dialog.accept)
        self.pushButton_2.clicked.connect(dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(dialog)
        
    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Ввод контакта"))
        self.lineEdit.setPlaceholderText(_translate("dialog", "Имя"))
        self.lineEdit_2.setPlaceholderText(_translate("dialog", "Телефон"))
        self.label.setText(_translate("dialog", "Дата рождения"))
        self.pushButton.setText(_translate("dialog", "ОК"))
        self.pushButton_2.setText(_translate("dialog", "Отмена"))

    def accept(self):
       
        print('ewgwet')
        if ((self.QDialog.label.text())):
            return(self.label.text(),45)
        else:
            return 3, 10

        # return self.lineEdit.text(), self.lineEdit_2.text()

    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    # 
    # edit_params__QD = Ui_dialog()
    #   ui = Ui_dialog()
    #   ui.setupUi(Dialog)
    #   Dialog.show()
    #   if (Dialog.exec_()):
    #     value1, value2 = edit_params__QD.accept()
    # 
    Dialog = QtWidgets.QDialog()
    ui = Ui_dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    a,b = Ui_dialog().accept()
    if (Dialog.exec_()):
        print(a,b,'запись соххраненна')
    else:
        print('запись НЕ соххраненна')
    # 
    sys.exit()